const Types = {
    unknown: 'unknown',

    airCondition: 'Air conditioner',
    blind: 'Blinds or Shutter',
    blindButtons: 'Blinds controlled only by buttons',
    button: 'Button',
    buttonSensor: 'buttonSensor',
    camera: 'IP Camera',
    chart: 'Chart',
    cie: 'CIE Color space',
    ct: 'Light with color temperature',
    dimmer: 'Light dimmer',
    door: 'Door sensor',
    fireAlarm: 'Fire alarm sensor',
    floodAlarm: 'Flood alarm sensor',
    gate: 'Gate',
    hue: 'Light with HUE color',
    humidity: 'Humidity',
    illuminance: 'Illuminance sensor',
    info: 'Information device (very simple)',
    image: 'image',
    instance: 'instance',
    light: 'Light switch',
    location: 'GPS Location',
    lock: 'Lock',
    media: 'Media',
    motion: 'Motion sensor',
    rgb: 'RGB Light (R,G,B have different states)',
    rgbSingle: 'RGB Light with hex color',
    rgbwSingle: 'RGBW Light with hex color',
    slider: 'Slider',
    socket: 'Socket',
    temperature: 'Temperature',
    thermostat: 'Thermostat',
    vacuumCleaner: 'Vacuum cleaner (robot)',
    volume: 'Volume',
    volumeGroup: 'Volume group',
    warning: 'Warning',
    weatherCurrent: 'Current weather',
    weatherForecast: 'Weather forecast',
    window: 'Window',
    windowTilt: 'Window that could be in tilted state',
};

module.exports = Types;
